In [20]:
import numpy as np

In [21]:
a=np.array([1,2,4,2,6,7,1])
x=np.where(a==2)
print(x)

(array([1, 3], dtype=int64),)


In [22]:
b=np.array([0,1,2,2,7,8,9])
y=np.searchsorted(b,3,side='left')
print(y)

4


In [23]:
c=np.array([9,5,2,7,6,4])
print(np.sort(c))

[2 4 5 6 7 9]


In [24]:
d=np.array([[7,4,6],[9,1,4]])
print(np.sort(d))

[[4 6 7]
 [1 4 9]]


In [27]:
e=np.array([31,78,69,88])
z=[False,True,False,True]
ne=e[z]
print(z)
print(ne)

[False, True, False, True]
[78 88]


In [29]:
filter_e=e<70
nee=e[filter_e]
print(filter_e)
print(nee)

[ True False  True False]
[31 69]
